In [1]:
import numpy as np
my_list=[1,2,3]
my_list
np.array(my_list)

array([1, 2, 3])

In [2]:
np.random.randint(1,100,10)

array([99, 66, 88, 38, 15, 51, 58, 47, 47, 47])

In [4]:
ar=np.random.randint(1,100,10)
print(ar)

[71 78  6 13 28 11 56 13 13  2]


In [7]:
ar.shape(5,5)

TypeError: 'tuple' object is not callable

In [10]:
ar.reshape(1,10)

array([[71, 78,  6, 13, 28, 11, 56, 13, 13,  2]])

In [11]:
ar.reshape(10,1)

array([[71],
       [78],
       [ 6],
       [13],
       [28],
       [11],
       [56],
       [13],
       [13],
       [ 2]])

In [13]:
ar.reshape(1,10).shape

(1, 10)

In [15]:
ar.dtype

dtype('int32')

In [16]:
ar+ar


array([142, 156,  12,  26,  56,  22, 112,  26,  26,   4])

In [17]:
ar*ar

array([5041, 6084,   36,  169,  784,  121, 3136,  169,  169,    4])

In [20]:
ar=np.arange(0,10)

In [21]:
ar/ar

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [22]:
ar**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [23]:
np.log(ar)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [25]:
ar=np.arange(0,11)

In [26]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
ar[8]

8

In [28]:
ar[1:5]

array([1, 2, 3, 4])

In [29]:
ar[0:5]

array([0, 1, 2, 3, 4])

In [32]:
ar[0:5]=100
print(ar)

[100 100 100 100 100   5   6   7   8   9  10]


In [34]:
ar=np.arange(0,11)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [35]:
ar>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [36]:
ar[ar>4]

array([ 5,  6,  7,  8,  9, 10])

In [37]:
ar=np.arange(12,0)
print(ar)

[]


In [38]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.ones(15)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.ten(5)

AttributeError: module 'numpy' has no attribute 'ten'

In [57]:
np.((3,3))

SyntaxError: invalid syntax (<ipython-input-57-50830592167c>, line 1)

In [1]:
np.arange(0,80,2)

NameError: name 'np' is not defined

In [2]:
import numpy as np
my_list=[1,2,3]
my_list
np.array(my_list)


array([1, 2, 3])

In [3]:
np.arange(0,80,2
         )

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78])

In [4]:
arr_list=[[0,1,2],[3,4,5],[6,7,8]]
np.array(arr_list)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr_list=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]
np.array(arr_list)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
    n = 4
    m = (2 * n) - 2
    for i in range(0, n):
        for j in range(0, m):
            print(end=" ")
        m = m - 1 
        for j in range(0, i + 1):
            print("*", end=' ')
        print(" ")

      *  
     * *  
    * * *  
   * * * *  
